# Generated by Django 5.1.2 on 2024-10-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
